=== Unit Testing Service Methods in Backend

==== Service Unit Testing Setup with Mockito

We need extra dependencies to support testing of the business methods in isolation.

. Add the following dependencies to the project:
+
[source,gradle]
----
testImplementation 'org.mockito:mockito-core:2.+'
testImplementation 'org.mockito:mockito-junit-jupiter:2.18.3'

testRuntime 'org.junit.jupiter:junit-jupiter-engine:5.3.1'
----
+
[TIP]
Finding configuration settings for your Gradle/Maven projects is very simple by searaching for them on MVNRepository: https://mvnrepository.com/

. If you also would like to run your project from Eclipse, add an additional dependency: 
+
[source,gradle]
----
testImplementation 'org.junit.platform:junit-platform-launcher:1.3.1'
----



. Create a test class (in case you don't already have one) `TestEventRegistrationService` in the corresponding package under `src/test/java`:
+
[source,java]
----
package ca.mcgill.ecse321.eventregistration.service;

import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;


@ExtendWith(MockitoExtension.class)
public class TestEventRegistrationService {

}
----

. Build your project to ensure its dependencies are correctly loaded.

==== Implementing Unit Tests for Service Class

. Add the following static imports for methods: 
+
[source,java]
----
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.fail;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.lenient;
import static org.mockito.Mockito.when;
----

. Add the following imports to the test class:
+
[source,java]
----
import java.sql.Date;
import java.sql.Time;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.invocation.InvocationOnMock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.mockito.stubbing.Answer;

import ca.mcgill.ecse321.eventregistration.dao.EventRepository;
import ca.mcgill.ecse321.eventregistration.dao.PersonRepository;
import ca.mcgill.ecse321.eventregistration.dao.RegistrationRepository;
import ca.mcgill.ecse321.eventregistration.model.Event;
import ca.mcgill.ecse321.eventregistration.model.Person;
import ca.mcgill.ecse321.eventregistration.model.Registration;
----



. Create the DAO mock for person 
+
[source,java]
----
@Mock
private PersonRepository personDao;

@InjectMocks
private EventRegistrationService service;

private static final String PERSON_KEY = "TestPerson";

@BeforeEach
public void setMockOutput() {
    lenient().when(personDao.findPersonByName(anyString())).thenAnswer( (InvocationOnMock invocation) -> {
        if(invocation.getArgument(0).equals(PERSON_KEY)) {
            Person person = new Person();
            person.setName(PERSON_KEY);
            return person;
        } else {
            return null;
        }
    });
}
----

. Add test cases from the link:https://gist.githubusercontent.com/imbur/d8836dc9f44ece65186a43ac80a259fd/raw/ff59449ad4dfadfc2c54bb317649300f6ae2409c/TestEventRegistrationService.java[complete test suite that is available from here].

. Run the tests as JUnit/Gradle tests and interpret the test error messages! You should see only a few (at least one) tests passing.

. Update the implementation (i.e., replace the current service method codes with the ones provided below) of the following methods with input validation in the `EventRegistrationService` service class to make the tests pass (we are rapid simulating a TDD process -- TDD stands for _Test-Driven Development_)
+
[source,java]
----
@Transactional
public Person createPerson(String name) {
	if (name == null || name.trim().length() == 0) {
		throw new IllegalArgumentException("Person name cannot be empty!");
	}
	Person person = new Person();
	person.setName(name);
	personRepository.save(person);
	return person;
}

@Transactional
public Person getPerson(String name) {
    if (name == null || name.trim().length() == 0) {
        throw new IllegalArgumentException("Person name cannot be empty!");
    }
    Person person = personRepository.findPersonByName(name);
    return person;
}

@Transactional
public Event getEvent(String name) {
    if (name == null || name.trim().length() == 0) {
        throw new IllegalArgumentException("Event name cannot be empty!");
    }
    Event event = eventRepository.findEventByName(name);
    return event;
}

@Transactional
public Event createEvent(String name, Date date, Time startTime, Time endTime) {
    // Input validation
    String error = "";
    if (name == null || name.trim().length() == 0) {
        error = error + "Event name cannot be empty! ";			
    }
    if (date == null) {
        error = error + "Event date cannot be empty! ";			
    }
    if (startTime == null) {
        error = error + "Event start time cannot be empty! ";			
    }
    if (endTime == null) {
        error = error + "Event end time cannot be empty! ";			
    }
    if (endTime != null && startTime != null && endTime.before(startTime)) {
        error = error + "Event end time cannot be before event start time!";			
    }
    error = error.trim();
    if (error.length() > 0) {
        throw new IllegalArgumentException(error);			
    }

    Event event = new Event();
    event.setName(name);
    event.setDate(date);
    event.setStartTime(startTime);
    event.setEndTime(endTime);
    eventRepository.save(event);
    return event;
}

@Transactional
public Registration register(Person person, Event event) {
    String error = "";
    if (person == null) {
        error = error + "Person needs to be selected for registration! ";
    } else if (!personRepository.existsById(person.getName())) {
        error = error + "Person does not exist! ";
    }
    if (event == null) {
        error = error + "Event needs to be selected for registration!";
    } else if (!eventRepository.existsById(event.getName())) {
        error = error + "Event does not exist!";
    }
    if (registrationRepository.existsByPersonAndEvent(person, event)) {
        error = error + "Person is already registered to this event!";
    }
    error = error.trim();

    if (error.length() > 0) {			
        throw new IllegalArgumentException(error);
    }

    Registration registration = new Registration();
	registration.setId(person.getName().hashCode() * event.getName().hashCode());
    registration.setPerson(person);
    registration.setEvent(event);

    registrationRepository.save(registration);

    return registration;
}

@Transactional
public List<Event> getEventsAttendedByPerson(Person person) {
    if (person == null ) {
        throw new IllegalArgumentException("Person cannot be null!");
    }
    List<Event> eventsAttendedByPerson = new ArrayList<>();
    for (Registration r : registrationRepository.findByPerson(person)) {
        eventsAttendedByPerson.add(r.getEvent());
    }
    return eventsAttendedByPerson;
}
----

. Run the tests again, and all should be passing this time.
 
==== Service Integration Testing with the curl Tool

The command line utility link:https://curl.haxx.se/[`curl`] is one way to automate integration testing for the REST API of your application. This brief section shows a basic examples for using it for testing with persons.

. Make sure you have a clean database for your integration tests. This can be done by using the `spring.jpa.hibernate.ddl-auto=create-drop` setting in the _application.properties_ file for the test backend, or by exposing a database clear API function that is only used durint integration testing.  

. Start the backend server.

. Issue `curl -s http://localhost:8080/persons` and observe the output!

. Use the `-X` switch to specify the used HTTP method:
+
```bash
$ curl -s -X POST http://localhost:8080/persons/testperson1
{"name":"testperson1","events":[]}
$ curl -s -X POST http://localhost:8080/persons/testperson2
{"name":"testperson2","events":[]}
$ curl -s -X http://localhost:8080/persons
[{"name":"testperson1","events":[]},{"name":"testperson2","events":[]}]
```
. To verify that a given content is in the returned values, you can use the standard output result of the command and filter it, for example, using `grep`
+
```bash
$ curl -s -X GET  http://localhost:8080/persons | grep -o testperson1
testperson1
```
. A way to get started with implementing a Gradle task for integration testing (expected in the second deliverable) is to call a command line tool (e.g., `curl`) from Gradle. Gradle documentation has a section on how to achieve this: https://docs.gradle.org/5.6.2/dsl/org.gradle.api.tasks.Exec.html#org.gradle.api.tasks.Exec
